version: "3.7"

services:
  vote:
    build: ./src/vote
    image: vote-webapp:1.0
    restart: on-failure
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    build: ./src/result
    image: result-webapp:1.0
    restart: on-failure
    depends_on:
      - "db"
    ports:
      # TODO: Map the host port 5001 to the
      # container's port 80.
      # https://docs.docker.com/compose/compose-file/#ports
      - "…"
    networks:
      - front-tier
      - back-tier

  worker:
    build: ./src/worker
    image: worker-app:1.0
    restart: on-failure
    depends_on:
      - "redis"
    networks:
      - back-tier

  redis:
    image: redis:5.0.5-alpine
    container_name: redis
    restart: on-failure
    networks:
      - back-tier

  db:
    image: postgres:11.4-alpine
    container_name: db
    restart: on-failure
    volumes:
      # TODO: Mount the host directory "./db-data"
      # to "/var/lib/postgresql/data" inside the
      # container so the DB is persistent.
      # https://docs.docker.com/compose/compose-file/#volumes
      - "…"
    networks:
      - back-tier

networks:
  front-tier:
  back-tier:
    internal: true
